export const emails = [
  {
    id: 1,
    sender: "Ingredia Nutrisha",
    email: "nutrisha@example.com",
    subject: "A collection of textile samples lay spread out on the table",
    time: "11:49 am",
    date: "20 May 2026",
    important: true,
    recipient: "Me, info@example.com",
    body: "Hi, Ingredia, A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.",
    attachments: ["My-Photo.png", "My-File.docx", "My-Resume.pdf"],
  },
  {
    id: 2,
    sender: "Almost unorthographic life",
    email: "life@ortho.io",
    subject:
      "One day however a small line of blind text by the name of Lorem Ipsum decided to leave",
    time: "10:30 am",
    date: "19 May 2026",
    important: false,
    recipient: "Me, team@office.com",
    body: "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    attachments: ["Design-Brief.pdf"],
  },
  {
    id: 3,
    sender: "Pointing has no control",
    email: "pointer@web.com",
    subject:
      "Pointing has no control about the blind texts it is an almost unorthographic life",
    time: "09:15 am",
    date: "19 May 2026",
    important: true,
    recipient: "Me, info@example.com",
    body: "The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen.",
    attachments: [],
  },
  {
    id: 4,
    sender: "Even the all-powerful",
    email: "power@domain.org",
    subject:
      "Even the all-powerful Pointing has no control about the blind texts",
    time: "08:45 am",
    date: "18 May 2026",
    important: false,
    recipient: "Me, info@example.com",
    body: "It returned ad hominem to its origin. However, the copywriter did not mind the little details. He continued his work on the project as if nothing had changed.",
    attachments: ["invoice_001.pdf", "receipt.jpg"],
  },
  {
    id: 5,
    sender: "Sansa Stark",
    email: "sansa@winterfell.com",
    subject: "The North Remembers our scheduled meeting",
    time: "07:20 am",
    date: "18 May 2026",
    important: true,
    recipient: "Me, info@example.com",
    body: "We need to discuss the logistics for the upcoming winter gala. Please ensure all banners are prepared and the guest list is finalized by Friday.",
    attachments: ["GuestList.csv"],
  },
  {
    id: 6,
    sender: "John Doe",
    email: "john.doe@techcorp.com",
    subject: "Weekly Project Sync-up",
    time: "06:10 pm",
    date: "17 May 2026",
    important: false,
    recipient: "Dev-Team",
    body: "Just a reminder that we have our weekly sync-up tomorrow at 10:00 AM. Please update your Jira tickets before the meeting.",
    attachments: ["Project_Timeline.xlsx"],
  },
  {
    id: 7,
    sender: "Jane Smith",
    email: "jane.smith@design.io",
    subject: "New Logo Concepts for Review",
    time: "05:45 pm",
    date: "17 May 2026",
    important: true,
    recipient: "Creative-Dept",
    body: "I've attached three new directions for the rebranding project. Let me know which one resonates most with the client's vision.",
    attachments: ["Logo_v1.png", "Logo_v2.png", "Logo_v3.png"],
  },
  {
    id: 8,
    sender: "Support Team",
    email: "support@cloudhost.com",
    subject: "Scheduled Maintenance Notification",
    time: "04:30 pm",
    date: "16 May 2026",
    important: false,
    recipient: "All Users",
    body: "Please be advised that we will be performing scheduled maintenance on our servers this Sunday from 2:00 AM to 4:00 AM UTC.",
    attachments: [],
  },
  {
    id: 9,
    sender: "Marketing Dept",
    email: "marketing@brand.com",
    subject: "Summer Campaign Results",
    time: "03:15 pm",
    date: "16 May 2026",
    important: false,
    recipient: "Me, info@example.com",
    body: "The results for the June campaign are in! We saw a 20% increase in engagement across all social platforms. Check the report for details.",
    attachments: ["Campaign_Report.pdf"],
  },
  {
    id: 10,
    sender: "Alex Rivers",
    email: "alex@freelance.net",
    subject: "Invoice for April Services",
    time: "02:00 pm",
    date: "15 May 2026",
    important: true,
    recipient: "Accounting",
    body: "Please find the attached invoice for the frontend development work completed in April. Let me know if you have any questions.",
    attachments: ["Invoice_APR_2026.pdf"],
  },
  {
    id: 11,
    sender: "Hiring Manager",
    email: "careers@startup.co",
    subject: "Interview Invitation: Frontend Developer",
    time: "01:20 pm",
    date: "15 May 2026",
    important: true,
    recipient: "Ayeza Bashir",
    body: "We were impressed with your GitHub profile! We'd like to invite you for a technical interview next Tuesday at 3:00 PM.",
    attachments: ["Interview_Guide.pdf"],
  },
  {
    id: 12,
    sender: "Google Alerts",
    email: "alerts@google.com",
    subject: "New results for 'React GSAP Animations'",
    time: "12:05 pm",
    date: "14 May 2026",
    important: false,
    recipient: "Me, info@example.com",
    body: "Your daily alert for new content matching your search criteria. Check out these latest articles on scroll-triggered animations.",
    attachments: [],
  },
  {
    id: 13,
    sender: "Product Team",
    email: "product@saas.com",
    subject: "Beta Access: New Dashboard Features",
    time: "11:45 am",
    date: "14 May 2026",
    important: true,
    recipient: "Beta Testers",
    body: "You've been selected to test our new analytics dashboard. Please log in and provide your feedback by EOD Friday.",
    attachments: ["Beta_Onboarding.pdf"],
  },
  {
    id: 14,
    sender: "Newsletter",
    email: "hello@css-tricks.com",
    subject: "What's New in Tailwind CSS v4.0",
    time: "10:30 am",
    date: "13 May 2026",
    important: false,
    recipient: "Subscribers",
    body: "Dive into the new CSS-first configuration and optimized build engine of Tailwind v4. It's a game changer for performance.",
    attachments: [],
  },
  {
    id: 15,
    sender: "Michael Scott",
    email: "m.scott@dundermifflin.com",
    subject: "Urgent Meeting in the Conference Room",
    time: "09:00 am",
    date: "13 May 2026",
    important: true,
    recipient: "All Staff",
    body: "Meeting in 5 minutes. No exceptions. We need to talk about the 'threat level midnight' situation immediately.",
    attachments: [],
  },
  {
    id: 16,
    sender: "GitHub",
    email: "noreply@github.com",
    subject: "[Security] Secret scanning alert for your repo",
    time: "08:15 am",
    date: "12 May 2026",
    important: true,
    recipient: "Ayeza Bashir",
    body: "We found a potential API key exposed in your public repository. Please revoke the key and update your security settings.",
    attachments: [],
  },
  {
    id: 17,
    sender: "Travel Agency",
    email: "bookings@holiday.com",
    subject: "Your E-Ticket for Paris",
    time: "07:40 am",
    date: "12 May 2026",
    important: false,
    recipient: "Me, info@example.com",
    body: "Your flight is confirmed! Please find your e-ticket and itinerary attached. We wish you a pleasant journey.",
    attachments: ["Itinerary.pdf", "Ticket.pdf"],
  },
  {
    id: 18,
    sender: "Slack",
    email: "notifications@slack.com",
    subject: "You have unread messages in #general",
    time: "06:55 am",
    date: "11 May 2026",
    important: false,
    recipient: "Me, info@example.com",
    body: "Your teammates have been busy! You have 12 unread messages waiting for you in the company Slack workspace.",
    attachments: [],
  },
  {
    id: 19,
    sender: "Finance App",
    email: "no-reply@finance.com",
    subject: "Monthly Expense Summary",
    time: "05:30 am",
    date: "11 May 2026",
    important: false,
    recipient: "Me, info@example.com",
    body: "Your monthly spending report for April is ready. You stayed within your budget for dining but exceeded the 'tech' category.",
    attachments: ["April_Report.pdf"],
  },
  {
    id: 20,
    sender: "Codewars",
    email: "stats@codewars.com",
    subject: "You've reached 4kyu! Keep it up!",
    time: "04:15 am",
    date: "10 May 2026",
    important: true,
    recipient: "Ayeza Bashir",
    body: "Congratulations on your rank up! Your logic skills are improving. Check out these new Kata challenges tailored for your level.",
    attachments: [],
  },
];
