export const allPermissions = [
  {
    id: 1,
    name: "Can add log entry",
    code: "add_logentry",
    type: "admin | log entry",
  },
  {
    id: 2,
    name: "Can change log entry",
    code: "change_logentry",
    type: "admin | log entry",
  },
  {
    id: 3,
    name: "Can delete log entry",
    code: "delete_logentry",
    type: "admin | log entry",
  },
  {
    id: 4,
    name: "Can view log entry",
    code: "view_logentry",
    type: "admin | log entry",
  },
  { id: 5, name: "Can add group", code: "add_group", type: "auth | group" },
  {
    id: 6,
    name: "Can change group",
    code: "change_group",
    type: "auth | group",
  },
  {
    id: 7,
    name: "Can delete group",
    code: "delete_group",
    type: "auth | group",
  },
  { id: 8, name: "Can view group", code: "view_group", type: "auth | group" },
  {
    id: 9,
    name: "Can add permission",
    code: "add_permission",
    type: "auth | permission",
  },
  {
    id: 10,
    name: "Can change permission",
    code: "change_permission",
    type: "auth | permission",
  },
  {
    id: 11,
    name: "Can delete permission",
    code: "delete_permission",
    type: "auth | permission",
  },
  {
    id: 12,
    name: "Can view permission",
    code: "view_permission",
    type: "auth | permission",
  },
  { id: 13, name: "Can add Blog", code: "add_blogs", type: "blog | Blog" },
  {
    id: 14,
    name: "Can change Blog",
    code: "change_blogs",
    type: "blog | Blog",
  },
  {
    id: 15,
    name: "Can delete Blog",
    code: "delete_blogs",
    type: "blog | Blog",
  },
  { id: 16, name: "Can view Blog", code: "view_blogs", type: "blog | Blog" },
  {
    id: 17,
    name: "Can add Category",
    code: "add_categories",
    type: "blog | Category",
  },
  {
    id: 18,
    name: "Can change Category",
    code: "change_categories",
    type: "blog | Category",
  },
  {
    id: 19,
    name: "Can delete Category",
    code: "delete_categories",
    type: "blog | Category",
  },
  {
    id: 20,
    name: "Can view Category",
    code: "view_categories",
    type: "blog | Category",
  },
  { id: 21, name: "Can add Meta", code: "add_metas", type: "blog | Meta" },
];
