export const config = [
  {

    id:1,name: "Site.favicon",
    value: "/media/Configurations/favicon_2klJcwk.png",
    title: "Favicon",
    inputType: "file",
  },
  { id:2,name: "Site.logo", value: "Logo", title: "Logo", inputType: "file" },
  { id:3,name: "Site.title", value: "Title", title: "Title", inputType: "text" },
  {
    id:4,name: "Site.tagline",
    value: "Tagline",
    title: "Tagline",
    inputType: "text",
  },
  { id:5,name: "Site.email", value: "Email", title: "Email", inputType: "text" },
  {
    id:6,name: "Site.status",
    value: "Status",
    title: "Status",
    inputType: "select",
  },
  {
    id:7,name: "Site.copyright_text",
    value: "Copyright Text",
    title: "Copyright Text",
    inputType: "text",
  },
  {
    id:8,name: "Site.footer_text",
    value: "Footer Text",
    title: "Footer Text",
    inputType: "text",
  },
  {
    id:9,name: "Site.coming_soon",
    value: "Coming Soon",
    title: "Coming Soon",
    inputType: "checkbox",
  },
  {
    id:10,name: "Site.contact",
    value: "Contact",
    title: "Contact",
    inputType: "text",
  },
  {
    id:11,name: "Site.opening_time",
    value: "Opening Time",
    title: "Opening Time",
    inputType: "text",
  },
  {
    id:12,name: "Site.address",
    value: "Address",
    title: "Address",
    inputType: "textarea",
  },
  {
    id:13,name: "Site.location",
    value: "Location",
    title: "Location",
    inputType: "text",
  },
  {
    id:14,name: "Site.logo_icon",
    value: "Logo Icon",
    title: "Logo Icon",
    inputType: "file",
  },
  {
    id:15,name: "Site.other_logo",
    value: "Other Logo",
    title: "Other Logo",
    inputType: "file",
  },
  {
    id:16,name: "Reading.show_on_front",
    value: "Show On Front",
    title: "Show On Front",
    inputType: "select",
  },
  {
    id:17,name: "Reading.nodes_per_page",
    value: "10",
    title: "Node Per Page",
    inputType: "number",
  },
  {
    id:18,name: "Social.linkedin",
    value: "Linkedin Url",
    title: "Linkedin",
    inputType: "text",
  },
  {
    id:19,name: "Social.facebook",
    value: "Facebook",
    title: "Facebook",
    inputType: "text",
  },
  {
    id:20,name: "Social.twitter",
    value: "Twitter Url",
    title: "Twitter",
    inputType: "text",
  },
  {
    id:21,name: "Widget.show_recent_post_widget",
    value: "1",
    title: "Show Recent Post Widget",
    inputType: "checkbox",
  },
  {
    id:22,name: "Widget.show_tag_widget",
    value: "1",
    title: "Show Tag Widget",
    inputType: "checkbox",
  },
  {
    id:23,name: "Widget.show_sidebar",
    value: "1",
    title: "Show Sidebar",
    inputType: "checkbox",
  },
  {
    id:24,name: "Widget.show_search_widget",
    value: "1",
    title: "Show Search Widget",
    inputType: "checkbox",
  },
  {
    id:25,name: "Widget.show_category_widget",
    value: "1",
    title: "Show Category Widget",
    inputType: "checkbox",
  },
  {
    id:26,name: "Widget.show_archive_widget",
    value: "1",
    title: "Show Archive Widget",
    inputType: "checkbox",
  },
  {
    id:27,name: "Site.home_slider",
    value: "Home Slider",
    title: "Home Slider",
    inputType: "select",
  },
  {
    id:28,name: "Site.support_email",
    value: "Support Email",
    title: "Support Email",
    inputType: "text",
  },
  { id:29,name: "Theme", value: "Theme", title: "Theme", inputType: "select" },
  { id:30,name: "Title", value: "Title", title: "Title", inputType: "text" },
  {
    id:31,name: "Site.name",
    value: "Site.name",
    title: "Site Name",
    inputType: "text",
  },
  {
    id:32,name: "sitefavicon",
    value: "Add Configurations",
    title: "Site Favicon",
    inputType: "file",
  },
  {
    id:33,name: "Web.Title.Logo",
    value: "web Logo",
    title: "Web Logo",
    inputType: "file",
  },
  {
    id:34,name: "Web.Title",
    value: "Web Title",
    title: "Web Title",
    inputType: "text",
  },
];
