export const allPages = [
  {
    id: 1,
    title: "About",
    content:
      "<h1>About Us</h1><p>Welcome to our professional frontend services.</p>",
    status: "Published",
    visibility: "Public",
    publishOn: "2022-12-05",
    createdAt: "Dec. 6, 2022, 10:56 a.m.",
    updatedAt: "Jan. 23, 2023, 5:37 p.m.",
    url: "/about",
    slug: "about",
    author: "w3@admin",
  },
  {
    id: 2,
    title: "Secret",
    content: "<p>This content is password protected.</p>",
    status: "Published",
    visibility: "Password Protected",
    publishOn: "2022-12-07",
    createdAt: "Dec. 8, 2022, 11:53 a.m.",
    updatedAt: "Jan. 17, 2023, 6:01 p.m.",
    url: "/secret",
    slug: "secret-page",
    author: "w3@manager",
  },
  {
    id: 3,
    title: "Home",
    content: "<h1>Home Page</h1><p>Welcome to the main experience.</p>",
    status: "Published",
    visibility: "Public",
    publishOn: "2022-12-03",
    createdAt: "Dec. 6, 2022, 10:45 a.m.",
    updatedAt: "Jan. 20, 2023, 3:03 p.m.",
    url: "/home",
    slug: "home",
    author: "w3@admin",
  },
];
